name: build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements 
        run: |
          pip install flake8
          pip install isort
          pip install pylint
      - name: Linting
        run: |
          isort -rc --check-only cvpods
          pylint --rcfile pylint.cfg ./cvpods 
          flake8 ./cvpods
      - name: Check docstring coverage
        run: |
          pip install interrogate
          interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 100 cvpods 
